services:
  ext-web:
    container_name: ext-web-next
    build:
      context: .
      dockerfile: Dockerfile.prod

    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
    ports:
      - "3000:3000"
    # command: ["sh", "-c", "npm i -f && npm run db:push && npm run start"]
    networks:
      - default
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: aiAgent
      POSTGRES_PASSWORD: aiAgent
      POSTGRES_DB: aiAgent
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: aiAgent
      MINIO_ROOT_PASSWORD: aiAgent
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  pgdata:
  minio_data:
